name: gaussian_mixture
num_components: 2
dim: 2
has_entropy: True

fn:
  _target_: targets.gaussian_mixture.GaussianMixtureModel
  num_components: ${target.num_components}
  dim: ${target.dim}
  log_Z: 0.
  can_sample: True
  sample_bounds: None

# Experiment-specific algorithm parameters
# !!! Default Parameters; Currently not tuned for this experiment !!!
# ----------------------------------------

dds: # Denoising Diffusion Sampler
  init_std: 5.
  step_size: 1e-3

gfn_tb: # Trajectory Balance
  reference_process: pinned_brownian  # pinned_brownian, ou, or ou_dds
  init_std: 5.  # for ou or ou_dss
  max_diffusion: 5.  # for pinned_brownian or ou
  step_size: 1e-3
  logZ_step_size: 1e-1
  init_logZ: 0.

gfn_tb_learn_bwd: # Trajectory Balance
  reference_process: pinned_brownian  # pinned_brownian, ou, or ou_dds
  init_std: 5.  # for ou or ou_dss
  max_diffusion: 5.  # for pinned_brownian or ou
  step_size: 1e-3
  logZ_step_size: 1e-1
  init_logZ: 0.

all: # Parameters that are shared between all algorithms
  batch_size: 2000
  iters: 20000
  milestones: [10000, 15000]
  num_steps: 64
  use_lp: False
  num_hid: 256